# Generated by Django 5.1.3 on 2024-12-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_platillos'),
        ),
    ]
