# Generated by Django 5.1.3 on 2024-12-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menu_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias_Comidas',
            new_name='CategoriasComidas',
        ),
        migrations.RenameModel(
            old_name='Sugerencias_Comidas',
            new_name='SugerenciasComidas',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='categoria_Comida',
            new_name='categoria_comida',
        ),
        migrations.RenameField(
            model_name='reservaciones',
            old_name='nombre',
            new_name='reservacion_nombre',
        ),
        migrations.AddField(
            model_name='menu',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
