# Generated by Django 5.1.3 on 2025-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_categorias_comidas_categoriascomidas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='platillo',
        ),
        migrations.DeleteModel(
            name='Reservaciones',
        ),
        migrations.RemoveField(
            model_name='sugerenciascomidas',
            name='categoria_comida',
        ),
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='SugerenciasComidas',
        ),
    ]
