# Generated by Django 5.1.3 on 2025-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pedidos_platillo_delete_reservaciones_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriasComidas',
            new_name='Foodscategories',
        ),
        migrations.RenameField(
            model_name='foodscategories',
            old_name='categoria',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='categoria_comida',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='platillo',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='precio',
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
