# Generated by Django 5.1.3 on 2025-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_categoriascomidas_foodscategories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodscategories',
            options={'verbose_name': 'categoria de comida', 'verbose_name_plural': 'categorias de comidas'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
